### ISSUE TITLE
Add missing README images

### ISSUE THREAD

**Issue by zenorocha** [zenorocha/react-email#117]
- [x] https://github.com/zenorocha/react-email/tree/main/packages/a
- [x] https://github.com/zenorocha/react-email/tree/main/packages/code
- [x] https://github.com/zenorocha/react-email/tree/main/packages/heading
- [x] https://github.com/zenorocha/react-email/tree/main/packages/hr
- [x] https://github.com/zenorocha/react-email/tree/main/packages/p
- [x] https://github.com/zenorocha/react-email/tree/main/packages/ul

**Comment by bukinoshita** [comment]
Let me know if you have any idea for any component. I still have to design them, but some of them I don't have a good idea what to do yet.

**Comment by zenorocha** [comment]
Some ideas from Apple:
* https://developer.apple.com/design/human-interface-guidelines/components/content/text-views
* https://developer.apple.com/design/human-interface-guidelines/components/content/image-views
* https://developer.apple.com/design/human-interface-guidelines/components/layout-and-organization/lists-and-tables

**Comment by zenorocha** [comment]
https://github.com/zenorocha/react-email/commit/cddcbf595cc81a482988c4cfe695ddce25425533
