### ISSUE TITLE
Build a "create-react-email" tool

### ISSUE THREAD

**Issue by zenorocha** [zenorocha/react-email#118]
Think of it as `create-react-app` but for email.

Similar:
* https://github.com/vercel/turborepo/tree/main/packages/create-turbo

**Comment by zenorocha** [comment]
Looks like https://www.npmjs.com/package/create-react-email is taken. I emailed the package author to see if he can transfer it to us. If not, I registered https://www.npmjs.com/package/create-email as a plan B.

**Comment by TAKANOME-DEV** [comment]
Hey @zenorocha, this package does not even have a github or there is something wrong because I'm getting a 404 page :thinking:  https://github.com/some1else/create-react-email

**Comment by corysimmons** [comment]
You can also reach out to npmjs.com's support team and they can free up the name of a dead package for you if you've already attempted to reach out to the package owner and they just never respond.

**Comment by EmersonGarrido** [comment]
I tried to contact him too, in parallel I will try to create...

**Comment by zenorocha** [comment]
We're going to use the [create-email](https://www.npmjs.com/package/create-email) package instead.
