### ISSUE TITLE
Create `Preview` component

### ISSUE THREAD

**Issue by zenorocha** [zenorocha/react-email#12]
A text snippet that appears under the subject line in the inbox but is hidden from the main email content when it’s opened.

Eg:

```jsx
import { Html } from '@react-email/html';
import { Preheader } from '@react-email/preheader';

const Email = () => {
  return (
    <Html lang="en">
      <Preheader text="Lorem ipsum" />
    </Html>
  );
};

**Comment by luanmuniz** [comment]
I think the name for that text is "Preview", maybe that's a better name.
Source: https://mailchimp.com/help/edit-your-emails-subject-preview-text-from-name-or-from-email-address/

**Comment by pepeladeira** [comment]
got this

**Comment by pepeladeira** [comment]
References:
- https://www.litmus.com/blog/the-ultimate-guide-to-preview-text-support
- https://www.litmus.com/blog/the-little-known-preview-text-hack-you-may-want-to-use-in-every-email/
