### ISSUE TITLE
Recreate Notion's magic link email

### ISSUE THREAD

**Issue by zenorocha** [zenorocha/react-email#122]
It's important that we try to recreate real emails in order to validate the quality and developer experience of our components. This is an example of a magic link email.

> Original: [Your temporary Notion login.eml.zip](https://github.com/zenorocha/react-email/files/9648292/Your.temporary.Notion.login.eml.zip)

<img width="648" alt="CleanShot 2022-09-26 at 10 12 26@2x" src="https://user-images.githubusercontent.com/398893/192339134-3a0562bb-1ec8-4d3f-9fee-0a0afe9aefc8.png">

**Comment by zenorocha** [comment]
Do you want to give it try on this one @guscsales? It includes a real code block ;)

**Comment by guscsales** [comment]
> Do you want to give it try on this one @guscsales? It includes a real code block ;)

PR opened here: https://github.com/zenorocha/react-email/pull/131

**Comment by zenorocha** [comment]
After testing in all email clients, this is 100% good to go :)
