### ISSUE TITLE
React-email as a builder (no integrations/apis)

### ISSUE THREAD

**Issue by cassiorsfreitas** [zenorocha/react-email#161]
Some email marketing tools like RD Station, Mailchimp, SendinBlue and so on, offer an interface to create a new email using only HTML. Something like that:

<img width="1436" alt="Screenshot 2022-10-26 at 12 05 33" src="https://user-images.githubusercontent.com/8185819/198014452-036a7541-58ba-472b-be98-8e74fde7c6ea.png">

And I was wondering if a second way to use this library would be just as a "builder". I mean, not necessarily an application that integrates with APIs and automates the whole process. It means, a React application running the @react-email library locally capable of generating the entire structure of an email after running a script, for example.

Actually, the library offers a good email development experience and many tools of this type don't have an APIs or a friendly APIs. Well, in these cases being able to use this library to "spit out" a ready-made HTML code sounds good, right?

**Comment by benjick** [comment]
Still no plans for this?
