### ISSUE TITLE
Add Code & Pre routes and components in the Manual Setup section

### ISSUE THREAD

**Issue by davidfcopozo** [zenorocha/react-email#210]
When you click on Code and/or Pre under Getting Started>Manual Setup section you'll get a 404 status code.

Replicate the issue:
Go to https://react.email/docs/getting-started/manual-setup
Click both Code and Pre cards.

Possible solution:

Adding both components to the components' folder [eact-email](https://github.com/zenorocha/react-email)/[apps](https://github.com/zenorocha/react-email/tree/main/apps)/[docs](https://github.com/zenorocha/react-email/tree/main/apps/docs)/[components](https://github.com/zenorocha/react-email/tree/main/apps/docs/components)

**Comment by bukinoshita** [comment]
This was removed since the components were deprecated. Fixed on the docs to reflect that. Thanks!
