### ISSUE TITLE
Add copy-to-clipboard and download button

### ISSUE THREAD

**Issue by zenorocha** [zenorocha/react-email#213]
<img width="543" alt="CleanShot 2022-12-06 at 23 29 27@2x" src="https://user-images.githubusercontent.com/398893/206073143-9a92ac18-890a-42fe-8138-2dc25aa3f638.png">

**Comment by b4s36t4** [comment]
@zenorocha Can I work on this?! and any references for this to work in all email clients?

**Comment by zenorocha** [comment]
https://github.com/zenorocha/react-email/commit/00d43c061a62b474089b1fc68b13db6ecfdc6e70
