### ISSUE TITLE
Preview shows files outside of repository (cache issue)

### ISSUE THREAD

**Issue by tony-schumacher** [zenorocha/react-email#218]
I created two project with react-email (Project A and Project B). 

When I open project B with `yarn dev`, it still shows the Email files of project A.
Also when I stop the script in the terminal, it quite often still runs in the background and I have to kill it with `killall node`.

**Comment by vvooycik** [comment]
I experience those too! Any workarounds for that? I got stuck with item that prevents compilation of the whole preview and cannot remove it!
