### ISSUE TITLE
Recreate Linear's email template

### ISSUE THREAD

**Issue by zenorocha** [zenorocha/react-email#225]
[Login for Linear.eml.zip](https://github.com/zenorocha/react-email/files/10197886/Login.for.Linear.eml.zip)

<img width="636" alt="image" src="https://user-images.githubusercontent.com/398893/206789211-3f18dc25-399a-45e2-8d9e-71fac6c3406e.png">

**Comment by Rychillie** [comment]
PR requested at [react-email-apps](https://github.com/zenorocha/react-email-apps/pull/38)

**Comment by EmersonGarrido** [comment]
It can close because it was done, it remains to go up in production.

This is updated in react-email-apps.
