### ISSUE TITLE
Recreate Yelp's email template

### ISSUE THREAD

**Issue by zenorocha** [zenorocha/react-email#226]
[New login to your Yelp account.eml.zip](https://github.com/zenorocha/react-email/files/10197905/New.login.to.your.Yelp.account.eml.zip)

<img width="638" alt="image" src="https://user-images.githubusercontent.com/398893/206789563-03f91921-51d4-4bca-8f09-f60b38e3d530.png">

**Comment by EmersonGarrido** [comment]
It can close because it was done, it remains to go up in production.

This is updated in react-email-apps.
