### ISSUE TITLE
Add support for `.jsx` files

### ISSUE THREAD

**Issue by vincentorback** [zenorocha/react-email#231]
The docs and local app asks for .tsx or .jsx files but only .tsx are parsed in the code and .jsx-files gives you a 404 page.
https://github.com/zenorocha/react-email/blob/18666c61c7b4ea28b1c83764b3d884c3469080a5/packages/react-email/preview/src/pages/preview/%5Bslug%5D.tsx#L17

PS. AMAZING project!

**Comment by zenorocha** [comment]
Thanks for reporting @vincentorback! Do you want to try to send a PR to fix this?

**Comment by vincentorback** [comment]
Gave it a go but I could not get the dev app started.
I believe it's just these three lines that need some glob checks for `.tsx`, `.jsx` and why not `.js`.

https://github.com/zenorocha/react-email/blob/18666c61c7b4ea28b1c83764b3d884c3469080a5/packages/react-email/preview/src/pages/index.tsx#L14

https://github.com/zenorocha/react-email/blob/18666c61c7b4ea28b1c83764b3d884c3469080a5/packages/react-email/preview/src/pages/preview/%5Bslug%5D.tsx#L17

https://github.com/zenorocha/react-email/blob/18666c61c7b4ea28b1c83764b3d884c3469080a5/packages/react-email/preview/src/pages/preview/%5Bslug%5D.tsx#L38
