### ISSUE TITLE
Create `.react-email` at the root of the package instead in the homedir

### ISSUE THREAD

**Issue by bukinoshita** [zenorocha/react-email#232]

**Comment by samtgarson** [comment]
+1 on this.

I believe this is a high priority issue—it's extremely rare, and pretty frustrating, to install a tool to test it and find that it has left trash in my home directory. Libraries accessing anything outside the current directory should be done with extreme prejudice for privacy reasons, IMO.

Particularly when it's completely opaque—there is no mention in the CLI output or the docs that this is happening, so a lot of users may never find out.

**Comment by bukinoshita** [comment]
Done and released under `canary`.
