### ISSUE TITLE
[Question] Why so many packages and not just one?

### ISSUE THREAD

**Issue by goenning** [zenorocha/react-email#295]
Really curious on this one, most component libraries have everything under a single package, why does react-email have one per component?

I personally think it'd be a lot easier for the maintainers and also those using the library, to have a single package.

**Comment by EmersonGarrido** [comment]
This is just for individual maintenance of the packages under development, but I believe that in the future we will unify the packages in a single package.

**Comment by ifeltsweet** [comment]
I also had the same question when I saw the documentation. It's a very unusual setup and quite inconvenient to work with as a user of react-email.
